//Download by http://www.NewXing.com
#if !defined(AFX_DATAFORMATDISP_H__E5D39613_32CA_49FD_BAA7_F67C7FC89406__INCLUDED_)
#define AFX_DATAFORMATDISP_H__E5D39613_32CA_49FD_BAA7_F67C7FC89406__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDataFormatDisp wrapper class

class CDataFormatDisp : public COleDispatchDriver
{
public:
	CDataFormatDisp() {}		// Calls COleDispatchDriver default constructor
	CDataFormatDisp(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDataFormatDisp(const CDataFormatDisp& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DATAFORMATDISP_H__E5D39613_32CA_49FD_BAA7_F67C7FC89406__INCLUDED_)
