//Download by http://www.NewXing.com
#if !defined(AFX_RDOERRORS_H__E154E555_CE59_45FF_B31C_AE74580E2D9B__INCLUDED_)
#define AFX_RDOERRORS_H__E154E555_CE59_45FF_B31C_AE74580E2D9B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CrdoError;

/////////////////////////////////////////////////////////////////////////////
// CrdoErrors wrapper class

class CrdoErrors : public COleDispatchDriver
{
public:
	CrdoErrors() {}		// Calls COleDispatchDriver default constructor
	CrdoErrors(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoErrors(const CrdoErrors& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CrdoError GetItem(const VARIANT& Index);
	void Clear();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RDOERRORS_H__E154E555_CE59_45FF_B31C_AE74580E2D9B__INCLUDED_)
