//Download by http://www.NewXing.com
#if !defined(AFX_RDOPARAMETERS_H__35127066_75A0_4FDB_8C93_8C319D12341A__INCLUDED_)
#define AFX_RDOPARAMETERS_H__35127066_75A0_4FDB_8C93_8C319D12341A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CrdoParameter;

/////////////////////////////////////////////////////////////////////////////
// CrdoParameters wrapper class

class CrdoParameters : public COleDispatchDriver
{
public:
	CrdoParameters() {}		// Calls COleDispatchDriver default constructor
	CrdoParameters(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoParameters(const CrdoParameters& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CrdoParameter GetItem(const VARIANT& Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RDOPARAMETERS_H__35127066_75A0_4FDB_8C93_8C319D12341A__INCLUDED_)
