//Download by http://www.NewXing.com
#if !defined(AFX_RDOPREPAREDSTATEMENTS_H__FB5F2D60_7A1D_4E87_B342_38A2E5D2AE37__INCLUDED_)
#define AFX_RDOPREPAREDSTATEMENTS_H__FB5F2D60_7A1D_4E87_B342_38A2E5D2AE37__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CrdoPreparedStatement;

/////////////////////////////////////////////////////////////////////////////
// CrdoPreparedStatements wrapper class

class CrdoPreparedStatements : public COleDispatchDriver
{
public:
	CrdoPreparedStatements() {}		// Calls COleDispatchDriver default constructor
	CrdoPreparedStatements(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoPreparedStatements(const CrdoPreparedStatements& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RDOPREPAREDSTATEMENTS_H__FB5F2D60_7A1D_4E87_B342_38A2E5D2AE37__INCLUDED_)
