//Download by http://www.NewXing.com
#if !defined(AFX_RDOQUERIES_H__F2BE0F0D_5642_43AA_9E7A_3E9703653224__INCLUDED_)
#define AFX_RDOQUERIES_H__F2BE0F0D_5642_43AA_9E7A_3E9703653224__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CrdoPreparedStatement;

/////////////////////////////////////////////////////////////////////////////
// CrdoQueries wrapper class

class CrdoQueries : public COleDispatchDriver
{
public:
	CrdoQueries() {}		// Calls COleDispatchDriver default constructor
	CrdoQueries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoQueries(const CrdoQueries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CrdoPreparedStatement GetItem(const VARIANT& Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RDOQUERIES_H__F2BE0F0D_5642_43AA_9E7A_3E9703653224__INCLUDED_)
