//Download by http://www.NewXing.com
#if !defined(AFX_RDORESULTSETS_H__BD8B66DD_4113_427F_9F7F_9C6A0CF8ABEC__INCLUDED_)
#define AFX_RDORESULTSETS_H__BD8B66DD_4113_427F_9F7F_9C6A0CF8ABEC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class C_rdoResultset;

/////////////////////////////////////////////////////////////////////////////
// CrdoResultsets wrapper class

class CrdoResultsets : public COleDispatchDriver
{
public:
	CrdoResultsets() {}		// Calls COleDispatchDriver default constructor
	CrdoResultsets(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoResultsets(const CrdoResultsets& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	C_rdoResultset GetItem(const VARIANT& Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RDORESULTSETS_H__BD8B66DD_4113_427F_9F7F_9C6A0CF8ABEC__INCLUDED_)
