//Download by http://www.NewXing.com
#if !defined(AFX_RDOTABLE_H__E4A94B95_68CA_4183_A4B4_C2E2F000F788__INCLUDED_)
#define AFX_RDOTABLE_H__E4A94B95_68CA_4183_A4B4_C2E2F000F788__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CrdoColumns;
class C_rdoResultset;

/////////////////////////////////////////////////////////////////////////////
// CrdoTable wrapper class

class CrdoTable : public COleDispatchDriver
{
public:
	CrdoTable() {}		// Calls COleDispatchDriver default constructor
	CrdoTable(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoTable(const CrdoTable& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CrdoColumns GetRdoColumns();
	CString GetName();
	BOOL GetUpdatable();
	long GetRowCount();
	CString GetType();
	C_rdoResultset OpenResultset(const VARIANT& Type, const VARIANT& LockType, const VARIANT& Options);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RDOTABLE_H__E4A94B95_68CA_4183_A4B4_C2E2F000F788__INCLUDED_)
