//Download by http://www.NewXing.com
#if !defined(AFX_RDOTABLES_H__6ADB6227_987D_40F2_8A4B_1443953426FD__INCLUDED_)
#define AFX_RDOTABLES_H__6ADB6227_987D_40F2_8A4B_1443953426FD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CrdoTable;

/////////////////////////////////////////////////////////////////////////////
// CrdoTables wrapper class

class CrdoTables : public COleDispatchDriver
{
public:
	CrdoTables() {}		// Calls COleDispatchDriver default constructor
	CrdoTables(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoTables(const CrdoTables& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	void Refresh();
	CrdoTable GetItem(const VARIANT& Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RDOTABLES_H__6ADB6227_987D_40F2_8A4B_1443953426FD__INCLUDED_)
